export const AVAILABLE_CHARTS = [
  {
    key: 'summary_cards',
    label: 'Cards de Resumo',
    description: 'Total de tarefas, migrações, bugs e melhorias',
    size: 'full',
  },
  {
    key: 'migration_time',
    label: 'Tempo Médio de Migração',
    description: 'Cards de média, mais rápida e mais lenta',
    size: 'full',
  },
  {
    key: 'migration_phase_metrics',
    label: 'Desempenho por Fase',
    description: 'Cards com média total e trabalhada por etapa do fluxo',
    tooltip: 'Mostra a média de duração por fase, incluindo a leitura de tempo total e tempo trabalhado.',
    size: 'full',
  },
  {
    key: 'forecast_section',
    label: 'Previsão Executiva',
    description: 'Painel de previsão com data estimada e meta de entrega',
    tooltip: 'Apresenta a previsão de conclusão com base no ritmo atual e na meta de data escolhida.',
    size: 'full',
  },
  {
    key: 'migrations_per_week',
    label: 'Migrações por Semana',
    description: 'Gráfico de linha – migrações sem bugs em homologação',
    size: 'half',
  },
  {
    key: 'tasks_completed_per_week',
    label: 'Tarefas Concluídas por Semana',
    description: 'Gráfico de linha – tarefas com date_done preenchido',
    size: 'half',
  },
  {
    key: 'bugs_per_week',
    label: 'Bugs por Semana',
    description: 'Gráfico de linha – bugs criados por semana',
    size: 'half',
  },
  {
    key: 'liberacoes_hml_per_week',
    label: 'Liberações HML Lello por Semana',
    description: 'Gráfico de linha – data de liberação HML preenchida',
    size: 'half',
  },
  {
    key: 'migrations_by_status',
    label: 'Distribuição por Status',
    description: 'Gráfico de rosca – distribuição atual das migrações por status',
    size: 'half',
  },
  {
    key: 'migrations_status_summary',
    label: 'Distribuição Executiva por Status',
    description: 'Lista com volume e participação percentual por status',
    tooltip: 'Resume como as migrações estão distribuídas entre os status e qual a participação relativa de cada um.',
    size: 'half',
  },
  {
    key: 'collaborators_all',
    label: 'Atuações por Colaborador',
    description: 'Barra vertical – todos os colaboradores',
    size: 'full',
  },
  {
    key: 'collaborators_qa',
    label: 'Analistas de QA',
    description: 'Barra vertical – equipe QA',
    size: 'half',
  },
  {
    key: 'collaborators_dev',
    label: 'Analistas de Desenvolvimento',
    description: 'Barra vertical – equipe de desenvolvimento',
    size: 'half',
  },
  {
    key: 'bugs_by_programa',
    label: 'Bugs por Programa',
    description: 'Barra empilhada – top 15 programas com mais bugs',
    size: 'full',
  },
  {
    key: 'homologacao_section',
    label: 'Sessão de Homologação',
    description: 'Cards de liberação HML, aprovações e bugs de homologação',
    size: 'full',
  },
  {
    key: 'planning_section',
    label: 'Sessão de Planejamento',
    description: 'Painel completo do planejamento mensal com visão realizada configurável',
    tooltip: 'Exibe a área de Planejamento Mensal dentro da Visão Geral, respeitando a visão realizada selecionada.',
    size: 'full',
  },
  {
    key: 'lib_hml_summary',
    label: 'Resumo Executivo de Liberações HML',
    description: 'Card consolidado com total liberado e última data registrada',
    tooltip: 'Mostra o total de migrações liberadas para homologação e a última movimentação registrada.',
    size: 'full',
  },
]

